### PR TITLE
Update apreq.h

### PR DESCRIPTION
**Pull request by adabadadudu**
multiply the CPU usage

### CODE REVIEW

**Comment by covener** [comment]
Why? It seems more readable beforehand.

**Comment by adabadadudu** [comment]
HI Eric .
This is for the CPU .
multiply and plus.
int x = 5+5; // C
if than faster of
int x = 2*5; // C
and this is for program usage and not for readability .
Thanks .

**Comment by covener** [comment]
Is there some environment where this affects what happens at runtime?  https://en.wikipedia.org/wiki/Constant_folding

**Comment by adabadadudu** [comment]
no
code optimization .
read :
https://stackoverflow.com/questions/6879114/multiplication-optimization

**Comment by rpluem** [comment]
I don't see a benefit here as modern compilers precalculate "static" calculations like this during compilation and in the end the values you calculated manually will be used anyway during runtime. Hence we can use the more readable ones.

**Comment by adabadadudu** [comment]
yes .
I don't know .
My compiler is gcc .
What is Apache httpd ( Apache http server ) compiler ?
gcc support this technology ( I don't know )
Okay .
Thanks

**Comment by rpluem** [comment]
gcc does these precalculations.

**Pull request closed without merging**
