### PR TITLE
fix assignment instead of comparison

### PR DESCRIPTION
**Pull request by ihsinme**
there is a mistake in the code. which is difficult to notice. I suggest the following fix.

### CODE REVIEW

**Comment by covener** [comment]
I think it is intentionally an assignment, otherwise  the passed in *names is not filled in

**Comment by ihsinme** [comment]
> I think it is intentionally an assignment, otherwise the passed in *names is not filled in

in my opinion your code may not be correct. I beg your pardon, but where there should be a comparison there cannot be an assignment.

**Comment by ylavic** [comment]
The code is admittedly not the clearest one, but its point is to assign the result of `prefix ? ... : ...` to both `name` **and** `names->elts[capture]` (cast omitted here).
The local variable/pointer `name` is to cache the result and avoid using an indirect addressing (`names->elts[capture]`) twice in the same block (uppercasing below).
That's valid `C` at least...

**Comment by notroj** [comment]
You can also see that this change causes the test cases to fail.

**Comment by ihsinme** [comment]
I'm sorry I wasted your time.

**Comment by notroj** [comment]
No time wasted, thank you for trying to improve the code!

**Pull request closed without merging**
