### PR TITLE
Enable TCP_FASTOPEN, if available.

### PR DESCRIPTION
**Pull request by ghost**
Note that it doesn't affect clients that do not support it.

### CODE REVIEW

**Comment by jimjag** [comment]
Where is that define enabled or checked for?

**Comment by ghost** [comment]
/usr/include/netinet/tcp.h:#define TCP_FASTOPEN      23 /\* Enable FastOpen on listeners */

**Comment by jimjag** [comment]
I would be best, I think, to check for this at build-time ala autoconf and use the normal HAVE_*. This also requires that APR be aware of it as well, to really be complete.

**Comment by candrews** [comment]
Can this please be reviewed/merged?

**Comment by candrews** [comment]
Reported in bugzilla at https://bz.apache.org/bugzilla/show_bug.cgi?id=63102

**Comment by HOSTED-POWER** [comment]
Is it still not implemented? Would be great if it was, very easy to fix apparently :| :)

**Pull request closed without merging**
