### PR TITLE
2.4.x: OpenSSL 3.0 compatibility fixes for mod_ssl

### PR DESCRIPTION
**Pull request by notroj**

### CODE REVIEW

**Comment by notroj** [comment]
One behaviour change (regression?) has been reported from testing this in Fedora.

With r1890067 (9eb262fb1a1957433c4bc072c292a36e3e6fe683) enabling the OpenSSL auto-DH-parameter selection *overrides* user-supplied DH parameters which are now ignored.  This is not necessary for OpenSSL 1.1 (which that patch affects) and is only removing a "deprecated" function so not strictly necessary for 3.0 either.  Need to ponder this one.

**Comment by sergiodj** [comment]
Hi @notroj,

We're starting our transition to OpenSSL 3 in Ubuntu and apache2 is one of the affected packages due to mod_ssl's incompatibility.  I've been monitoring the situation here to check what's going to happen with this PR, but decided to ping you directly and check if there are any news regarding it, specifically when considering the possible regression you mentioned above.

For what's worth, I backported this set of patches to our current apache2 package in Ubuntu and was able to verify that they build fine with OpenSSL 3.  We have some automated tests (autopkgtests) for the package, and they seem to succeed as well.

Thanks.

**Comment by rpluem** [comment]
> One behaviour change (regression?) has been reported from testing this in Fedora.
> 
> With r1890067 ([9eb262f](https://github.com/apache/httpd/commit/9eb262fb1a1957433c4bc072c292a36e3e6fe683)) enabling the OpenSSL auto-DH-parameter selection _overrides_ user-supplied DH parameters which are now ignored. This is not necessary for OpenSSL 1.1 (which that patch affects) and is only removing a "deprecated" function so not strictly necessary for 3.0 either. Need to ponder this one.

Any update on this? Is this fixed by r1893876 (dd5f2cc3dfffafd8c26db4d7bb9571085aed050a) and r1893964 (e77dffef9aa80fa1a7f90b49214dccc3ce957c51) on trunk? Would you propose to merge this to 2.4.x if these two revisions are added?

**Comment by notroj** [comment]
I found one more bug when testing a debug build.  I will fix that too and then propose the backport.

**Comment by minfrin** [comment]
Backported to v2.4.52 as follows:

```
  *) mod_ssl: Updates to support OpenSSL 3.x
     trunk patch: https://svn.apache.org/r1519264
                  https://svn.apache.org/r1737657
                  https://svn.apache.org/r1876934
                  https://svn.apache.org/r1876936
                  https://svn.apache.org/r1876938
                  https://svn.apache.org/r1890067
                  https://svn.apache.org/r1890076
                  https://svn.apache.org/r1891138
                  https://svn.apache.org/r1893876
                  https://svn.apache.org/r1893964
                  https://svn.apache.org/r1894716
                  https://svn.apache.org/r1895774
     backport PR: https://github.com/apache/httpd/pull/258
     2.4.x patch: https://patch-diff.githubusercontent.com/raw/apache/httpd/pull/258.patch
                  or https://people.apache.org/~jorton/mod_ssl-openssl3.patch
     +1: jorton, minfrin, ylavic
```

**Comment by ylavic** [comment]
Merged in r1895868 (769bc2137ac4d146fd6e632688d4afec6658755c).

**Pull request closed without merging**
