### PR TITLE
Test travis notifications

### PR DESCRIPTION
**Pull request by elukey**
Sorry for the spam :)

### CODE REVIEW

**Comment by Humbedooh** [comment]
test test, ignore me :)

**Comment by Humbedooh** [comment]
one more test...

**Comment by Humbedooh** [comment]
test test test

**Comment by Humbedooh** [comment]
bla bla :)

**Comment by Humbedooh** [comment]
this should hit the new notifications list :)

**Comment by notroj** [comment]
@elukey I think we are good here, can close this PR?

**Pull request closed without merging**
