### PR TITLE
Do not hard-define empty env var

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

This PR solves issue #59371 :
https://bz.apache.org/bugzilla/show_bug.cgi?id=59371

Thank you 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
I Would also be very glad to see this backported to 2.4.x.
Many thx 👍

**Comment by benrubson** [comment]
Hi,
Could we think about merging this ?
Thank you very much 👍 
Ben

**Comment by covener** [comment]
I am not sure this is safe to backport, it might be reasonable for people to be using empty native environment variables, e.g. when things are deactivated.  It seems better to address the overlap between the different kinds of interpolation

**Comment by benrubson** [comment]
Thank you for your feedback Eric 👍 
Mmmmh you think that some may intentionally use `MYVAR=` "instead" of just running `unset MYVAR`.
Regarding the overlap issue you are talking about, to be honest, I'm not sure I'll be able to correct it :|

**Pull request closed without merging**
