### PR TITLE
Icing/http2 2.0

### PR DESCRIPTION
**Pull request by icing**
New version of mod_http2 using pollsets. Sync with trunk for the module. Incorporates changes:

```
1894163 1894169 1894172 1894181 1894184 1894189 1894190 1894192 1894220 1894226 1894228 1894241 1894252 1894728 1894949
```

### CODE REVIEW

**Comment by ylavic** [comment]
Rebuild

**Comment by ylavic** [comment]
On Xenial:
```
Cannot load /home/travis/build/httpd-root/modules/mod_http2.so into server: /home/travis/build/httpd-root/modules/mod_http2.so: undefined symbol: apr_file_pipe_create_pools
```

You possibly want to disable `H2_POLL_STREAMS` for APR < 1.6 (Xenial ships 1.5)..

**Comment by icing** [comment]
The APR sales rep, who sold me this feature, never mentioned this!

**Comment by ylavic** [comment]
Never trust a sales ;)

**Pull request closed without merging**
